### ISSUE TITLE
FR: Package google-appengine-python

### ISSUE THREAD

**Issue by ogarcia** [sudoforge/pkgbuilds#1]
Could you package `app-engine-python` and `app-engine-python-extras`? Would be great :smile:

**Comment by sudoforge** [comment]
@ogarcia I'll be releasing the additional component packages within the next week. Until then, you can follow the instructions [detailed in a pinned AUR comment][0] for managing any additional components you may need.

[0]: https://aur.archlinux.org/packages/google-cloud-sdk#pinned-659642-content
