### ISSUE TITLE
google-cloud-sdk 264.0.0-1 failes to build (cannot import name json_format)

### ISSUE THREAD

**Issue by hashworks** [sudoforge/pkgbuilds#10]
```
$ makepkg -sir .
==> Making package: google-cloud-sdk 264.0.0-1 (Wed 25 Sep 2019 02:32:46 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading google-cloud-sdk_264.0.0.orig.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29.9M  100 29.9M    0     0  41.3M      0 --:--:-- --:--:-- --:--:-- 41.2M
  -> Found google-cloud-sdk.sh
==> Validating source files with sha256sums...
    google-cloud-sdk_264.0.0.orig.tar.gz ... Passed
    google-cloud-sdk.sh ... Passed
==> Extracting sources...
  -> Extracting google-cloud-sdk_264.0.0.orig.tar.gz with bsdtar
==> Starting prepare()...
  -> Checking for newer upstream release
  -> This AUR release: 264.0.0
  -> Latest upstream release: 264.0.0
  -> Everything up to date :)
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
  -> Copying core SDK components
  -> Running bootstrapping script
Traceback (most recent call last):
  File "/var/cache/makepkg/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/bin/bootstrapping/install.py", line 12, in <module>
    import bootstrapping
  File "/var/cache/makepkg/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 46, in <module>
    from googlecloudsdk.core.updater import update_manager
  File "/var/cache/makepkg/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 39, in <module>
    from googlecloudsdk.core.resource import resource_printer
  File "/var/cache/makepkg/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_printer.py", line 42, in <module>
    from googlecloudsdk.core.resource import config_printer
  File "/var/cache/makepkg/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/resource/config_printer.py", line 25, in <module>
    from googlecloudsdk.core.resource import resource_printer_base
  File "/var/cache/makepkg/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_printer_base.py", line 46, in <module>
    from googlecloudsdk.core.resource import resource_projector
  File "/var/cache/makepkg/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_projector.py", line 69, in <module>
    from google.protobuf import json_format as protobuf_encoding
ImportError: cannot import name json_format
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by hashworks** [comment]
Note: `263.0.0-1` build just fine

**Comment by sudoforge** [comment]
Packages are built in a containerized environment during a `pre-commit` hook, so it's unlikely that I'll be able to reproduce this on a clean machine -- but perhaps I skipped over something obvious when updating the package late last night.

I'll take a look when I get the chance later today. In the mean time, can you attempt to ensure you're building in a clean environment and let me know if you receive the same error?

**Comment by hashworks** [comment]
Hm, you're right. Works on another machine. I'll close this for now and compare the machines. Sorry for your time.

**Comment by sudoforge** [comment]
Are you, by chance, using an AUR helper to build? I see in your initial comment that you've executed `makepkg`, but was this the first attempt at building `google-cloud-sdk`, or was an AUR helper used initially?

**Comment by hashworks** [comment]
Yes, `yay` was used initially.

**Comment by sudoforge** [comment]
On the same machine in which you see the error, try cloning the repository inside a temporary location:

```
$ cd /tmp
$ git clone https://aur.archlinux.org/google-cloud-sdk.git
```

and then building that manually:

```
$ makepkg -sri .
```

If you get that same error, then it's possible that there's an unlisted `makedep` that, for whatever reason, is present on working machines and not present on your machine -- perhaps something in `base` that you removed from your non-working machine.

If you don't get that same error, then this indicates that the way in which `yay` is handling upgrades and/or installations is not "safe" in the sense that they are not performed in a clean environment. I would try blowing away the repository and cache (if one exists) that `yay` creates, and try to re-install with `yay`.

I personally use [`aurutils`][0] to maintain AUR packages in a Pacman repository, which is added to my Pacman configuration. This means I install, remove, and upgrade AUR packages on my system the same way that I do regular packages: using `pacman -Suy`. You may find this workflow more consistent than `yay` or other similar build-and-install-in-place AUR helpers.

[0]: https://aur.archlinux.org/packages/aurutils/

**Comment by sudoforge** [comment]
The specific error your original comment references is an odd one; the line producing that error is:

```
from google.protobuf import json_format as protobuf_encoding
```

This is a pretty straightforward import in Python. The `google.protobuf` package is bundled in with `google-cloud-sdk`, so I can't think of any possible reason that the standard workflow of cloning and running `makepkg` would fail. Admittedly, I do not use `yay` and have no clue what it's doing under the hood, but it would seem to be breaking the upgrade in this particular scenario.

**Comment by hashworks** [comment]
Cloning the repository in `/tmp` and running `makepkg -sri .` resulted in the same error, so I'm reopening the issue as you suggested.

**Comment by sudoforge** [comment]
Can you pass the output of `diff <(pacman -Qg base base-devel) <(pacman -Sg base base-devel)`, executed on the machine with the failing environment?

**Comment by hashworks** [comment]
Nothing special:
```
30a31
> base nano
46a48
> base vi
```

**Comment by sudoforge** [comment]
Thanks. Please bear with me -- I'm not able to recreate this at all, so I'm going to request that you try one more thing on your failing machine:

```
$ cd /tmp/google-cloud-sdk # (or git clone it again if you've deleted it)
$ git clean -fdx
$ mkarchroot /tmp/buildroot base base-devel
$ makechrootpkg -c -r /tmp/buildroot -- -sr
```

This will build it in a chroot, which the `mkarchroot` command will be creating and installing `base` and `base-devel` to. `makechrootpkg` will then execute `makepkg` inside this "root", which should be a clean environment.

**Comment by hashworks** [comment]
No stress, I'm grateful for your support :)

Your `makechrootpkg` example gave me an error:
```
makechrootpkg -c -r /tmp/buildroot -- -sr
==> Synchronizing chroot copy [/tmp/buildroot/root] -> [hashworks]...done
==> ERROR: /tmp/buildroot/hashworks/etc/makepkg.conf not found.
    Aborting...
==> ERROR: Could not download sources.
```

Since I haven't worked with makechrootpkg directly before I used the wrapper `extra-x86_64-build`, which created the chroot `/var/lib/archbuild/extra-x86_64/` and build the package sucessfully there.

**Comment by hashworks** [comment]
Got it, I had google protobuf installed in `/usr/lib/python2.7/site-packages/google/protobuf/`, but it wasn't owned by any pacman or pip package. Removing it resolved the issue.

**Comment by sudoforge** [comment]
> but it wasn't owned by any pacman or pip package

Well, that explains why I wasn't able to recreate it!

Glad you got it sorted out; thanks for the update.
