### ISSUE TITLE
google-cloud-sdk build is broken

### ISSUE THREAD

**Issue by bswartz** [sudoforge/pkgbuilds#11]
==> Starting package()...
Copying core SDK components
Running bootstrapping script
/home/arch/google-cloud-sdk/PKGBUILD: line 38: python2: command not found
==> ERROR: A failure occurred in package().
    Aborting...

**Comment by sudoforge** [comment]
@bswartz I replied to your comment on the AUR:

https://aur.archlinux.org/packages/google-cloud-sdk/#comment-715059

This was fixed prior to the issue being opened by [`b188232f330c`](https://github.com/sudoforge/pkgbuilds/commit/b188232f330c9d26b05ff16d62387cdaf831e798).
