### ISSUE TITLE
TypeError when using any gcloud command

### ISSUE THREAD

**Issue by blackhatbrigade** [sudoforge/pkgbuilds#15]
I'm getting the error 
```
/opt/google-cloud-sdk/lib/third_party/ipaddress/__init__.py:1106: SyntaxWarning: str object is not callable; perhaps you missed a comma?
  raise TypeError("%s and %s are not of the same version" (a, b))
```
whenever I issue any gcloud command.

**Comment by sudoforge** [comment]
I am unable to recreate this in a fresh, sandboxed environment, at least when running `gcloud topic startup` or `gcloud auth list`, which, without signing in, is about the extent of what I can test at the moment.

Can you provide a few things for me?

* A specific command that you are running
* The output of `pacman -Qi google-cloud-sdk`
* The output of `uname -a`

Thanks ahead of time! I'm working today and have a long drive tonight, but may be able to take a look early tomorrow morning (I'm in a UTC-7 timezone, for context).

**Comment by n0vember** [comment]
Hi,

Having the same issue here, I can provide with the details:

- pacman -Qi google-cloud-sdk

```
Name            : google-cloud-sdk
Version         : 278.0.0-1
Description     : A set of command-line tools for the Google Cloud Platform. Includes gcloud (with beta and alpha commands), gsutil, and bq.
Architecture    : x86_64
URL             : https://cloud.google.com/sdk/
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : python  python2
Optional Deps   : python-crcmod: [gsutil] verify the integrity of GCS object contents
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 179,89 MiB
Packager        : Unknown Packager
Build Date      : mer. 29 janv. 2020 10:36:19 CET
Install Date    : mer. 29 janv. 2020 10:38:43 CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

- uname -a

`Linux tatsuo 5.4.15-arch1-1 #1 SMP PREEMPT Sun, 26 Jan 2020 09:48:50 +0000 x86_64 GNU/Linux`

As for the command, I didn't see any that did not present the problem:

```
gcloud compute instances list
/opt/google-cloud-sdk/lib/third_party/ipaddress/__init__.py:1106: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  raise TypeError("%s and %s are not of the same version" (a, b))
...
```

```
gcloud compute ssh XXX
/opt/google-cloud-sdk/lib/third_party/ipaddress/__init__.py:1106: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  raise TypeError("%s and %s are not of the same version" (a, b))
...
```

**Comment by sudoforge** [comment]
Thank you for the response @n0vember. I was able to take a look when I got back last night and it looks like upstream project (`google-cloud-sdk`) depends on an outdated version of a third party dependency, `ipaddress`. I've added a patch for the issue here, and have reported it upstream:

https://issuetracker.google.com/issues/148752648

**Comment by n0vember** [comment]
That works great, thank you :)
