### ISSUE TITLE
google-cloud-sdk-app-engine-python{,-extras} creates an erroneous directory structure

### ISSUE THREAD

**Issue by sudoforge** [sudoforge/pkgbuilds#39]
> captain commented on 2021-02-08 18:15
> I think there is an error in PKGBUILD line 22:
> 
> ```
> mkdir -p "${pkgdir}/opt/google-cloud-sdk/platform/google_appengine"
> ```
> 
> I think it should be:
> 
> ```
> mkdir -p "${pkgdir}/opt/google-cloud-sdk/platform"
> ```
> Right now this results in the creation of `${pkgdir}/opt/google-cloud-sdk/platform/google_appengine/google_appengine` when line 35 is run:
> 
> ```
> cp -R \
>   "${srcdir}/google-cloud-sdk/platform/google_appengine" \
>   "${pkgdir}/opt/google-cloud-sdk/platform/google_appengine"
> ```

From https://aur.archlinux.org/packages/google-cloud-sdk-app-engine-python/#comment-790646

---

cc @shvelo

**Comment by shvelo** [comment]
Thanks @sudoforge for fixing this so quickly.  
I've also made this change in my google-cloud-sdk-app-engine-java package which I've derived from google-cloud-sdk-app-engine-python.  
Let me know if you'd be willing to adopt google-cloud-sdk-app-engine-java.

**Comment by sudoforge** [comment]
> Let me know if you'd be willing to adopt `google-cloud-sdk-app-engine-java`

I'd be happy to. Feel free to transfer maintainer to my AUR account, `sudoforge`, and I'll take it from there (because repository commit history can't be overwritten in the AUR [except by TUs], there's a certain process for adopting existing packages into this repository.
