### ISSUE TITLE
Move wee-slack to /usr/share

### ISSUE THREAD

**Issue by trygveaa** [sudoforge/pkgbuilds#40]
As of version 2.9 of weechat, it can load scripts from `/usr/share/weechat/python`, see https://github.com/weechat/weechat/pull/1461. Additionally, as of version 2.7.0 of wee-slack, `weemoji.json` can be loaded from `/usr/share/weechat`, see https://github.com/wee-slack/wee-slack/commit/14ea3ef85acfa3e08ee067fb3fe4dcb0342327f5.

I therefore suggest installing to these locations instead of `/usr/lib`. That would allow users to load the script directly, without creating any symlink (except for autoloading), and you can remove those post installation instructions.

**Comment by sudoforge** [comment]
Thanks for opening this issue! I was just reading through the changelog this morning and noting these (very welcome) changes.
