### ISSUE TITLE
Installing additional components does not work

### ISSUE THREAD

**Issue by janhicken** [sudoforge/pkgbuilds#5]
The `PKGBUILD` file contains a variable called `_additional_components`, which a user can append any components, that should be installed in the bootstrap process.

However, this does not work currently, because the `"disable_updater"` setting in `opt/google-cloud-sdk/lib/googlecloudsdk/core/config.json` prevents it. The setting seems to apply for the bootstrap process, too.

I suggest setting it to `true` just for the call of `…/bootstrapping/install.py` and setting it back afterwards.

**Comment by sudoforge** [comment]
> I suggest setting it to true just for the call of …/bootstrapping/install.py and setting it back afterwards.

This probably isn't going to happen; I've been backed up a bit but am going to be releasing the additional components as separate packages soon.
