### ISSUE TITLE
installing google-cloud-sdk breaks with python 3.10.0 installed

### ISSUE THREAD

**Issue by alias-rahil** [sudoforge/pkgbuilds#50]
```
Traceback (most recent call last):
  File "/home/rahil/.cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/bin/bootstrapping/install.py", line 12, in <module>
    import bootstrapping
  File "/home/rahil/.cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 46, in <module>
    from googlecloudsdk.core.updater import update_manager
  File "/home/rahil/.cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 39, in <module>
    from googlecloudsdk.core.console import progress_tracker
  File "/home/rahil/.cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/console/progress_tracker.py", line 651, in <module>
    class _BaseStagedProgressTracker(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: google-cloud-sdk
```

What worked for me was downgrading to python 9 first then installing google-cloud-sdk.

**Comment by sudoforge** [comment]
python 3.10.0 is currently in testing and is not available in `core`, but thanks for flagging this!

An issue was filed upstream about a month ago: https://issuetracker.google.com/issues/205238176

I've reached out to Felix (the maintainer of `core/python`) to get an understanding of the timeline for `python-3.10.0` being promoted from `testing` to `core`, and it should be no more than a few days. I've left a comment on the upstream issue tracker letting them know this.

Although it is currently assigned to an upstream team member, I have doubts that a fix will be in place by the time that `python-3.10.0` is promoted to `core`. I'm in the middle of prepping for a trip, but should be able to make some time Monday evening (UTC-07:00) to work on generating patches for `google-cloud-sdk`.

I'll keep this issue open for tracking.

**Comment by ZephireNZ** [comment]
python 3.10 is out in core now, just tried to upgrade and got the above error.

Sounds like you're already on it, thanks in advance 😊

**Comment by flassagne** [comment]
You can find an analysis here https://issuetracker.google.com/issues/205005959?pli=1

**Comment by catwell** [comment]
In the meantime you can use Python 2.7 with:  `CLOUDSDK_PYTHON=python2`

**Comment by sudoforge** [comment]
Had a moment this morning so I added a quick-n-dirty patch for all broken symbol imports that I could find (with the limited time I had). The changes made should be backwards compatible.

 Pinning this issue for visibility.

Please test out your usage of `google-cloud-sdk` (and related packages), and report here or open a new issue if you encounter issues (with any supported version of Python).

**Comment by gbatiz** [comment]
Just did a clean build and it installed fine :+1:

**Comment by flassagn** [comment]
Thank @sudoforge works for me !
