### ISSUE TITLE
google-cloud-sdk: fix patch 0004

### ISSUE THREAD

**Issue by tzvetkoff** [sudoforge/pkgbuilds#51]
In commit 44574830 you removed the `# Python 3.3 and above.` comments from the .patch by simply editing the file - this, unfortunately, breaks it as the hunk sizes are now wrong.
You'd need to either revert the comments back in the patch so the hunk sizes are correct, or regenerate the patch.

**Comment by Zeeshan-2k1** [comment]
-> Extracting google-cloud-sdk_367.0.0.orig.tar.gz with bsdtar
==> Starting prepare()...
failed to apply patch: 0004-collections-abc.patch
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: google-cloud-sdk


I am getting this error while building the SDK.
OS: Arch Linux

**Comment by sudoforge** [comment]
Absolutely accurate -- looks like the caching issue that affected the pipeline _wasn't_ fixed. It is now, and I'll have a rebuild out in a moment. Please bear with me.

**Comment by sudoforge** [comment]
Thank you for bringing this to my attention. 100% human error, and I apologize for the inconvenience.

Patches should be landing in the AUR about now.
