### ISSUE TITLE
google-cloud-sdk: collections-abc.patch is broken

### ISSUE THREAD

**Issue by janhicken** [sudoforge/pkgbuilds#54]
The build for the `google-cloud--sdk` in version `368.0.0` currently fails, because the `0004-collections-abc.patch` cannot be applied.

```
failed to apply patch: 0004-collections-abc.patch
```

It seems Google has fixed parts of the issue upstream, however other parts of the patch still seem to be required.

I tried removing the patch from the build and the following error occurred:

```
ERROR: gcloud crashed (CommandLoadFailure): Problem loading gcloud.functions.list: module 'collections' has no attribute 'Mapping'.
```

**Comment by TheLinuxNinja** [comment]
Same here, pkgver=368.0.0

```
failed to apply patch: 0004-collections-abc.patch
==> ERROR: A failure occurred in prepare().
Aborting...
-> error making: google-cloud-sdk
```

**Comment by l1f** [comment]
+1

**Comment by amrit073** [comment]
+1

**Comment by jld3103** [comment]
+1

**Comment by sudoforge** [comment]
Hey folks,

Sorry for the late night push that caused this -- I had a spotty connection and bypassed the tests that run pre-commit as it requires multiple downloads, which kept getting interrupted / timing out. As soon as I'm done traveling, this will all be moved to run as part of the CI/CD system for these packages.

---

Please avoid "+1" comments. Reacting to an issue with the thumbs up emoji is a great way to say "I'm experiencing this too" (for bugs), or "I like this idea, too" (for suggestions/requests). Beyond that, the +1 comment is excess noise, as it sends an email to everyone involved in the thread, without contributing meaningful content.

**Comment by amiga23** [comment]
It seems the patch is partly applied upstream. 
I've removed the >/dev/null and get the following concrete error messages:
```
==> Starting prepare()...
patching file bin/dev_appserver.py
patching file bin/endpointscfg.py
patching file completion.zsh.inc
patching file lib/googlecloudsdk/api_lib/run/k8s_object.py
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file lib/googlecloudsdk/api_lib/run/k8s_object.py.rej
patching file lib/googlecloudsdk/api_lib/run/traffic.py
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file lib/googlecloudsdk /api_lib/run/traffic.py.rej
patching file lib/third_party/dns/namedict.py
patching file lib/third_party/frozendict/__init__.py
patching file lib/third_party/functools32/functools32.py
patching file lib/third_party/ml_sdk/cloud/ml/prediction/prediction_utils.py
patching file lib/third_party/prompt_toolkit/styles/from_dict.py
patching file platform/gsutil/gslib/vendored/boto/boto/dynamodb/types.py
patching file platform/gsutil/gslib/vendored/boto/boto/mws/connection.py
failed to apply patch: 0004-collections-abc.patch
==> ERROR: A failure occurred in prepare().
    Aborting...
```
