### ISSUE TITLE
bazelisk(-bin): Shell completions

### ISSUE THREAD

**Issue by uhthomas** [sudoforge/pkgbuilds#57]
It would be nice to include shell completions with the packages. See the [Bazel community package](https://github.com/archlinux/svntogit-community/blob/packages/bazel/trunk/PKGBUILD) for an example.  I understand this isn't ideal as Bazelisk could technically be any version of Bazel but at least it's something. There is an open issue (https://github.com/bazelbuild/bazelisk/issues/29) which discusses this briefly. I see you've taken a look at this before 😄 .

**Comment by sudoforge** [comment]
I think this is something that should be handled within Bazelisk, especially considering that the proposed solution is inadequate (for the reason you stated). Opening this has caused me to revisit bazebuild/bazelisk#29 however, and I have a little time this weekend to work on a more robust solution over there.
