### ISSUE TITLE
google-cloud-sdk error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ginjiruu** [sudoforge/pkgbuilds#58]
Full error was 
/opt/google-cloud-sdk/platform/bundledpythonunix/bin/python3: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
Previously installed version 371 on an arch laptop running python 3.10 as well as arch via wsl2 with python 3.10 installed

**Comment by sudoforge** [comment]
Please provide the following:

* Your build process (tools that you're using; commands that you ran)
* The full output of the build process
* The output of `env | grep CLOUDSDK` in the environments you've experienced the error in
* The output of `command -v python ; which python` when executed within the same environments you are experiencing the error in

**Comment by ginjiruu** [comment]
Your build process (tools that you're using; commands that you ran)
    Used paru as my aur helper
The full output of the build process


> paru -S google-cloud-sdk
> :: Resolving dependencies...
> :: Calculating conflicts...
> :: Calculating inner conflicts...
> 
> Aur (1) google-cloud-sdk-372.0.0-1
> 
> :: Proceed to review? [Y/n]: y
> 
> :: Downloading PKGBUILDs...
>  PKGBUILDs up to date
>  nothing new to review
> fetching devel info...
> ==> Making package: google-cloud-sdk 372.0.0-1 (Tue 15 Feb 2022 12:21:35 PM EST)
> ==> Retrieving sources...
>   -> Found google-cloud-sdk_372.0.0.orig.tar.gz
>   -> Found google-cloud-sdk.sh
>   -> Found 0001-set-python2-for-dev-appserver-py.patch
>   -> Found 0002-set-python2-for-endpointscfg-py.patch
>   -> Found 0003-add-compdef-to-zsh-completion.patch
>   -> Found 0004-collections-abc.patch
> ==> Validating source files with sha256sums...
>     google-cloud-sdk_372.0.0.orig.tar.gz ... Passed
>     google-cloud-sdk.sh ... Passed
>     0001-set-python2-for-dev-appserver-py.patch ... Passed
>     0002-set-python2-for-endpointscfg-py.patch ... Passed
>     0003-add-compdef-to-zsh-completion.patch ... Passed
>     0004-collections-abc.patch ... Passed
> ==> Making package: google-cloud-sdk 372.0.0-1 (Tue 15 Feb 2022 12:21:36 PM EST)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Found google-cloud-sdk_372.0.0.orig.tar.gz
>   -> Found google-cloud-sdk.sh
>   -> Found 0001-set-python2-for-dev-appserver-py.patch
>   -> Found 0002-set-python2-for-endpointscfg-py.patch
>   -> Found 0003-add-compdef-to-zsh-completion.patch
>   -> Found 0004-collections-abc.patch
> ==> Validating source files with sha256sums...
>     google-cloud-sdk_372.0.0.orig.tar.gz ... Passed
>     google-cloud-sdk.sh ... Passed
>     0001-set-python2-for-dev-appserver-py.patch ... Passed
>     0002-set-python2-for-endpointscfg-py.patch ... Passed
>     0003-add-compdef-to-zsh-completion.patch ... Passed
>     0004-collections-abc.patch ... Passed
> ==> Removing existing $srcdir/ directory...
> ==> Extracting sources...
>   -> Extracting google-cloud-sdk_372.0.0.orig.tar.gz with bsdtar
> ==> Starting prepare()...
> ==> Sources are ready.
> google-cloud-sdk-372.0.0-1: parsing pkg list...
> :: google-cloud-sdk-372.0.0-1 is up to date -- skipping build
> [sudo] password for administrator: 
> loading packages...
> resolving dependencies...
> looking for conflicting packages...
> 
> Packages (1) google-cloud-sdk-372.0.0-1
> 
> Total Installed Size:  630.91 MiB
> 
> :: Proceed with installation? [Y/n] 
> (1/1) checking keys in keyring                     [----------------------] 100%
> (1/1) checking package integrity                   [----------------------] 100%
> (1/1) loading package files                        [----------------------] 100%
> (1/1) checking for file conflicts                  [----------------------] 100%
> (1/1) checking available disk space                [----------------------] 100%
> :: Processing package changes...
> (1/1) installing google-cloud-sdk                  [----------------------] 100%
> Optional dependencies for google-cloud-sdk
>     python2: for dev_appserver.py and endpointscfg support [installed]
>     python-crcmod: [gsutil] verify the integrity of GCS object contents
> :: Running post-transaction hooks...
> (1/1) Arming ConditionNeedsUpdate...

The output of env | grep CLOUDSDK in the environments you've experienced the error in
    produced not output

The output of command -v python ; which python when executed within the same environments you are experiencing the error in
    /usr/bin/python
    /usr/bin/python

**Comment by ginjiruu** [comment]
Sorry I missed your comments edit on the AUR. This is an error that occurs when running the the cli via the AUR package. 
Installing via pipe to bash instructions on googles end work just fine.

**Comment by sudoforge** [comment]
so it's a _usage_ error, not a _build_ error?

what `gcloud` command(s) are you running that produces the error? can you provide the stacktrace?

**Comment by ginjiruu** [comment]
Any command I run generates that output and I am not sure how I would send a stack trace for this. 
This 
`/opt/google-cloud-sdk/platform/bundledpythonunix/bin/python3: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory` is the complete output it provides no matter the command. Even with `--help` appended.

Sorry if this is now the wrong place to have placed the issue.

**Comment by sudoforge** [comment]
okay, well it looks like you're not getting the environment variables set from the [file that's added to `/etc/profile.d`](https://github.com/sudoforge/pkgbuilds/blob/master/google-cloud-sdk/google-cloud-sdk.sh). this is apparent because you're using the bundled python3, as you can see from the error -- this is used when `CLOUDSDK_PYTHON` isn't set (and the bundled python exists and is executable).

can you double check that `/etc/profile.d/google-cloud-sdk.sh` is installed, and contains the same contents as the main tree of this repository does?

**Comment by ginjiruu** [comment]
Thank you very much. For some reason fish was no longer sourcing my /etc/profile which was causing the issue. 
I used the work around with bass from here https://wiki.gentoo.org/wiki/Fish#fish_as_a_default_shell_with_bash_as_the_login_shell

Thank's a ton!

**Comment by sudoforge** [comment]
TIL. That is really, really, really, really, really, really, _terrible_ behavior for a shell.
