### ISSUE TITLE
`google-cloud-sdk`: Can't build as `root` or with `sudo`.

### ISSUE THREAD

**Issue by will-ca** [sudoforge/pkgbuilds#59]
```
$ sudo pamac install google-cloud-sdk

[…]

  File "/var/cache/private/pamac/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/configurations/named_configs.py", line 549, in _ActiveConfigNameFromFile
    raise NamedConfigFileAccessError(
googlecloudsdk.core.configurations.named_configs.NamedConfigFileAccessError: Active configuration name could not be read from: [/root/.config/gcloud/active_config]. Ensure you have sufficient read permissions on required active configuration in [/root/.config/gcloud/configurations].
  Unable to read file [/root/.config/gcloud/active_config]: [Errno 13] Permission denied: '/root/.config/gcloud/active_config'
==> ERROR: A failure occurred in package().
    Aborting...
Finished with result: exit-code
Main processes terminated with: code=exited/status=4
```

I tried various combinations of `sudo`, `bash -c`, `su`, and environment variables. The result was the same failure in each case.

Running `makepkg` as a regular user and using `sudo` for the install afterwards works.

But it is a bit more trouble. It means GUI package managers with update reminders or CLI tools with blanket `update` commands and such don't work, and also in turn means losing some automatic caching of build files.

**Comment by sudoforge** [comment]
As a rule, I do not support third-party AUR helpers (and encourage other package maintainers to take the same stance), as I do not have the bandwidth to look through Pamac and determine where its error is. This is not an issue with the package, but with `pamac` attempting to install the package as root, as it shouldn't even allow this behavior in the first place

Running `makepkg` as root is not allowed:

https://github.com/archlinux/devtools/blob/fa5afbc30b68912eb7f16d434a27faf787c3da9c/makechrootpkg.in#L355-L358

(commit `fa5afbc30b68912eb7f16d434a27faf787c3da9c` is the latest on that file as of the writing of this comment)

**Comment by sudoforge** [comment]
Some additional thoughts...

> It means GUI package managers with update reminders or CLI tools with blanket update commands and such don't work

If these tools you mention also execute the `PKGBUILD` instructions as the root user, then yes, they will fail with the same error.

> ... also in turn means losing some automatic caching of build files

What, specifically, are you talking about here?

**Comment by will-ca** [comment]
Right. Maybe I should look into whether Pamac's doing something wrong, then.

> Can you provide specific examples that show how the package build instructions are not caching files in the way you expect?

I just mean how running `pamac install` repeatedly will only download the `PKGBUILD` and source repos once. It looks like they just go in various places in `/tmp/` and `/var/tmp`. Naturally redoing the build in my home directory means downloading everything again. Just a Pamac behaviour, and at most a minor UX inconvenience. Really it's more the bulk updating that I'm missing.
