### ISSUE TITLE
google-cloud-sdk: set CLOUDSDK_PYTHON to /usr/bin/python

### ISSUE THREAD

**Issue by blueyed** [sudoforge/pkgbuilds#62]
I think it would be good to use `export CLOUDSDK_PYTHON=/usr/bin/python` (instead of just `python`) in `/etc/profile.d/google-cloud-sdk.sh`, so that it would not use the Python binary from `$PATH` (e.g. an activated virtualenv).

(It is relevant with e.g. `gcloud beta compute ssh …`, which might suggest to install NumPy, which might be missing in the virtualenv.)

**Comment by sudoforge** [comment]
Given that this is installed at the system level, I think this is a fine idea. Thanks for the suggestion!
