### ISSUE TITLE
AUR shows bazelisk version 1.10.1-1 when 1.11.0 is available here

### ISSUE THREAD

**Issue by jmelahman** [sudoforge/pkgbuilds#63]
this package was upgraded here to `1.11.0` with https://github.com/sudoforge/pkgbuilds/commit/499dc29663d8fc2afa29217592b82969417079aa. Not sure when that is expected to reflect in the aur, https://aur.archlinux.org/packages/bazelisk, but it still shows `1.10.1`

**Comment by sudoforge** [comment]
Thanks for bringing this to my attention! These packages are built, tested, and deployed using an internal CI pipeline, and a change made several months ago caused the pipelines for `bazelisk` and `bazelisk-bin` to fail to export to the AUR. This has been remedied and the packages have been updated.
