### ISSUE TITLE
google-cloud-sdk fails to build

### ISSUE THREAD

**Issue by vpzomtrrfrt** [sudoforge/pkgbuilds#67]
I get this error when trying to build `google-cloud-sdk`:

```
==> Starting prepare()...
failed to apply patch: 0004-collections-abc.patch
==> ERROR: A failure occurred in prepare().
    Aborting...
```

**Comment by sudoforge** [comment]
Strange, this is a definitive error, but CI passed. I'll have to dig into that tomorrow. Thanks for opening an issue and bringing this to my attention.
