### ISSUE TITLE
Bundle google-cloud-sdk component gke-gcloud-auth-plugin

### ISSUE THREAD

**Issue by EvyBongers** [sudoforge/pkgbuilds#68]
Using kubectl against GKE, I get this message:

> W0523 11:31:21.399966   60779 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
> To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

Is it possible to bundle this component with the `google-cloud-sdk` package?
Or, alternatively, create a separate package to install the component separately?

Current version:
```
$ pacman -Q google-cloud-sdk 
google-cloud-sdk 386.0.0-1
$ gcloud -v    
Google Cloud SDK 386.0.0
alpha 2022.05.13
beta 2022.05.13
bq 2.0.74
bundled-python3-unix 3.9.12
core 2022.05.13
gsutil 5.10
```

**Comment by sudoforge** [comment]
Hey, thanks for opening an issue about this. I'll look into creating a separate package for this (because I'm interested in maintaining it).
