### ISSUE TITLE
Error installing firebase-tools

### ISSUE THREAD

**Issue by chclxds** [sudoforge/pkgbuilds#74]
==> Starting package()...
find: The current directory is included in the PATH environment variable, which is unsafe in combination with find's -execdir action. Please remove the current directory from your $PATH (ie remove ".", double colon or colon at the beginning or end)
==> ERROR: A failure occurred in package().
    Aborting...

**Comment by sudoforge** [comment]
PATH is not modified as part of the build process when using `makepkg` and friends.

All of these packages are built in a clean chroot before commits are landed. The environment they build on is a bare-bones Arch Linux system with `base`, `base-devel`, and that's about it.

This does not occur in the pipeline (runs on my homelab infrastructure for now), nor on my own Arch Linux workstation.

---

Please detail your environment, including your Linux distribution, the version of `find` you have installed, and the commands you run to build the package.

**Comment by chclxds** [comment]
sorry, unfortunately I had to format the machine and after that, it worked perfectly
