### ISSUE TITLE
Is google-cloud-sdk still maintained?

### ISSUE THREAD

**Issue by pintert3** [sudoforge/pkgbuilds#77]
It's been nearly 2 months since the last google-cloud-sdk update. Is it still maintained? Any help needed?

**Comment by dR3b** [comment]
There are some open questions about python2 https://github.com/sudoforge/pkgbuilds/issues/73

**Comment by jeroenj** [comment]
Hi @sudoforge, is there anything I/we can do to help out with this? Or would you prefer to transfer ownership/maintenance of this to someone else?

**Comment by esemeniuc** [comment]
Bump for this as well!
